INSERT INTO additional_server (id, name, server_dir, command, image_url)
VALUES (0, 'AVS Code', 'C:\Program Files\Microsoft VS Code', 'C:\Program Files\Microsoft VS Code\Code.exe',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png'),
       (1, 'BVS Code', 'C:\Program Files\Microsoft VS Code', 'C:\Program Files\Microsoft VS Code\Code.exe',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png'),
       (2, 'CVS Code', 'C:\Program Files\Microsoft VS Code', 'C:\Program Files\Microsoft VS Code\Code.exe',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png'),
       (3, 'VS Code', 'C:\Program Files\Microsoft VS Code', 'C:\Program Files\Microsoft VS Code\Code.exe',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png'),
       (4, 'VS Code', 'C:\Program Files\Microsoft VS Code', 'C:\Program Files\Microsoft VS Code\Code.exe',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png'),
       (5, 'EVS Code', 'C:\Program Files\Microsoft VS Code', 'C:\Program Files\Microsoft VS Code\Code.exe',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png'),
       (6, 'VS Code', 'C:\Program Files\Microsoft VS Code', 'C:\Program Files\Microsoft VS Code\Code.exe',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png'),
       (7, 'VS Code', 'C:\Program Files\Microsoft VS Code', 'C:\Program Files\Microsoft VS Code\Code.exe',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png'),
       (8, 'GVS Code', 'C:\Program Files\Microsoft VS Code', 'C:\Program Files\Microsoft VS Code\Code.exe',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png'),
       (9, 'VS Code', 'C:\Program Files\Microsoft VS Code', 'C:\Program Files\Microsoft VS Code\Code.exe',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png');