spring.profiles.active=docker

steamcmd.cache.path=/home/steam/Steam/config/config.vdf

# File upload limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver